server:
  port: 8080
spring:
  application:
    name: user
  datasource:
    username: barak
    password: 9088007
    url: jdbc:postgresql://localhost:5432/user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
