server:
  port: 8081
spring:
  application:
    name: group
  datasource:
    username: barak
    password: 9088007
    url: jdbc:postgresql://localhost:5432/groups
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true